#ifndef SOCKETEXCEPTION_H
#define SOCKETEXCEPTION_H

#define SOCKET_RUNTIME_ERROR -1

#define SOCKET_RUNTIME_SUCCESS 0x0
#define SOCKET_LISTENING_ERROR -2
#define SOCKET_BIND_ERROR -3
#define RUNTIME_CODE int

#endif